# Generated by Django 4.1.3 on 2022-11-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('datetime_captured', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date captured')),
                ('avg_cpu_usage', models.FloatField(verbose_name='overall cpu usage')),
                ('virtual_memory_usage', models.FloatField(verbose_name='overall memory usage')),
                ('virtual_memory_capacity', models.FloatField(verbose_name='max memory capacity')),
                ('disk_usage', models.FloatField(verbose_name='disk usage')),
                ('disk_capacity', models.FloatField(verbose_name='disk capacity')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compyterstats.computer')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(verbose_name='process id')),
                ('cpu_usage', models.FloatField(verbose_name='cpu usage per process')),
                ('name', models.CharField(max_length=30)),
                ('io_counter', models.CharField(max_length=30)),
                ('memory_data', models.FloatField()),
                ('virtual_memory_data', models.FloatField()),
                ('origin_timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compyterstats.timestamp')),
            ],
        ),
    ]
